name: carpooling
description: Mobile carpooling application.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  rxdart: ^0.27.1
  flutter_bloc: ^7.1.0
  http: ^0.13.3
  location: ^4.3.0

  # Firebase dependencies
  firebase_core: ^1.4.0
  firebase_analytics: ^8.2.0

  cloud_firestore: ^2.4.0

  scoped_model: ^2.0.0-nullsafety.0
  equatable: ^2.0.3
  font_awesome_flutter: ^9.1.0
  line_icons: ^2.0.1
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^2.1.0
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.4

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  fonts:
    - family: EncodeCondensed
      fonts:
        - asset: assets/fonts/Encode_Sans_Condensed/EncodeSansCondensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/Encode_Sans_Condensed/EncodeSansCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Encode_Sans_Condensed/EncodeSansCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/Encode_Sans_Condensed/EncodeSansCondensed-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Encode_Sans_Condensed/EncodeSansCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/Encode_Sans_Condensed/EncodeSansCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Encode_Sans_Condensed/EncodeSansCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/Encode_Sans_Condensed/EncodeSansCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Encode_Sans_Condensed/EncodeSansCondensed-Black.ttf
          weight: 900
  #fonts:
  # - family: EncodeSansCondensed
  #fonts:
  # - asset: assets/fonts/Encode_Sans_Condensed/EncodeSansCondensed-Light.ttf
  #- asset: assets/fonts/Encode_Sans_Condensed/EncodeSansCondensed-Regular.ttf
